---
output:
  pdf_document: default
  html_document: default
---
# Methods

## Exploratory Data Analysis

First of all, we had to check, if there are missing values inside of the data-set. Therefore we used the following code to proof this:

```{r}
#| echo = TRUE,
#| message = TRUE
summary(is.na(dataWithCategory))
```
As it can be seen, there were $`r sum(is.na(dataWithCategory$state))`$ missing values inside the column "state".


## Folgendes nur zur Übersicht/weiteren Aufbau(Gliederung)



3. Methods, for example:
- Descriptive statistics
- Variable distributions
- Statements about variances and co-variance and missing values
- Chosen analytical procedures to answer the research question


Inhalt/Aufbau:
  1:EDA (Exploratory Data Analysis) auf Datenset    anwenden
    1.1: including information on the variables’ distribution, missing values,
categories / grouping factors (if applicable) and the relationships between the variables, especially
regarding the variable in focus, for example, the dependent variable of a applied statistical method (if
applicable)
  2:Methoden/statistische Modelle aufstellen