

```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)
library(maps)
library(janitor)

#Initial data
rawData <- read_delim("02-data/cost-of-living-2017.csv", 
                                  delim = "\t", escape_double = FALSE, 
                                  trim_ws = TRUE)
rawData <- janitor::clean_names(rawData)
manipulatedData <- rawData[,3:4] %>% group_by(country) %>% summarise(average = mean(cost_of_living_plus_rent_index))

colnames(manipulatedData)[1] <- "region"

world <- map_data("world")
worldSubset <- left_join(manipulatedData, world, by="region")
worldSubset

plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)
worldCLI <- ggplot(data = worldSubset, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) +
  geom_polygon(aes(fill = average)) +
  scale_fill_distiller(palette ="RdBu", direction = 1) + # or direction=1
  ggtitle("Average Cost of Living + Rent Index") +
  plain +
  guides(fill = FALSE)  
worldCLI
```


```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)
library(maps)
library(janitor)

#initial country data
dd <- read_delim("02-data/developed_and_developing_countries.csv", 
                                  delim = ";", escape_double = FALSE,
                                  trim_ws = TRUE)
dd <- janitor::clean_names(dd)
dd$category[dd$category == "developed"] <- 1.0
dd$category[dd$category == "developing"] <- 0.0
dd$category <- as.double(dd$category)

dd$category[dd$category == "developing"] <- 0.0
dd$country[dd$country == "italy"] <- "Italy"

colnames(dd)[1] <- "region"
colnames(dd)[2] <- "development"

world <- map_data("world")
worldSubset <- left_join(dd, world, by="region")

worldSubset

plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)
worldDD <- ggplot(data = worldSubset, mapping = aes(x = long, y = lat, group = group)) +
  borders("world", fill="grey90",colour="grey") + 
  coord_fixed(1.3) +
  geom_polygon(aes(fill = development)) +
  scale_fill_distiller(palette ="RdBu", direction = 1) + # or direction=1
  ggtitle("Industrialized and developing countries") +
  plain
worldDD
```

```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)
library(maps)
library(janitor)

#Initial data
rawData <- read_delim("02-data/cost-of-living-2017.csv", 
                                  delim = "\t", escape_double = FALSE, 
                                  trim_ws = TRUE)
rawData <- janitor::clean_names(rawData)
rawData

dd <- read_delim("02-data/developed_and_developing_countries.csv", 
                                  delim = ";", escape_double = FALSE,
                                  trim_ws = TRUE)
dd <- janitor::clean_names(dd)

colnames(dd)[2] <- "development"
dd$development[dd$development == "developed"] <- 1.0
dd$development[dd$development == "developing"] <- 0.0
dd$development <- as.double(dd$development)

dd$development[dd$development == "developing"] <- 0.0
dd$country[dd$country == "italy"] <- "Italy"
dd

data <- left_join(dd, rawData, by="country")
data

plot(data$cost_of_living_plus_rent_index,data$development
     ,xlab = "Cost of Living plus rent index", ylab = "Development state")

plot(data$groceries_index,data$rent_index
     ,xlab = "Cost of Living plus rent index", ylab = "Rent Index")

data$development[data$development == 1.0] <- "developed"
data$development[data$development == 0.0] <- "developing"
data

boxplot(data$cost_of_living_plus_rent_index~data$development)
```
